############# English navigation ##############

# main menu
[[main]]
name = "Acasa"
url = "alexandrabarbu.ro/"
weight = 1

[[main]]
name = "Despre"
url = "alexandrabarbu.ro/despre/"
weight = 4

[[main]]
name = "Terapii"
url = "alexandrabarbu.ro/terapii/"
weight = 5

[[main]]
name = "Blog"
url = "alexandrabarbu.ro/blog/"
weight = 7

[[main]]
weight = 9
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Career"
  url = "alexandrabarbu.ro/career/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Pricing"
  url = "alexandrabarbu.ro/pricing/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "Blog Details"
  url = "alexandrabarbu.ro/blog/post-1/"
  weight = 3

  [[main]]
  parent = "Pages"
  name = "Alexandra Barbu"
  url = "alexandrabarbu.ro/autor/Alexandra-Barbu/"
  weight = 4

  [[main]]
  parent = "Pages"
  name = "Job Details"
  url = "alexandrabarbu.ro/career/job-post-1/"
  weight = 5

  [[main]]
  parent = "Pages"
  name = "Case Studies"
  url = "alexandrabarbu.ro/case-studies/"
  weight = 6

  [[main]]
  parent = "Pages"
  name = "Case Studies Details"
  url = "alexandrabarbu.ro/case-studies/case-1/"
  weight = 7

  [[main]]
  parent = "Pages"
  name = "Terms & Conditions"
  url = "alexandrabarbu.ro/terms-and-conditions/"
  weight = 8

  [[main]]
  parent = "Pages"
  name = "Changelog"
  url = "alexandrabarbu.ro/changelog/"
  weight = 9

  [[main]]
  parent = "Pages"
  name = "Sign In"
  url = "alexandrabarbu.ro/signin/"
  weight = 10

  [[main]]
  parent = "Pages"
  name = "Elements"
  url = "alexandrabarbu.ro/alexandrabarbu.ro/elements/"
  weight = 11

[[main]]
name = "Contact"
url = "alexandrabarbu.ro/alexandrabarbu.ro/contact/"
weight = 15


# footer menu
[[footer]]
name = "About"
url = "alexandrabarbu.ro/about/"
weight = 1

[[footer]]
name = "How It Works"
url = "alexandrabarbu.ro/how-it-works/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "alexandrabarbu.ro/terms-and-conditions/"
weight = 3

[[footer]]
name = "Changelog"
url = "alexandrabarbu.ro/changelog/"
weight = 4
